# django-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGlzZ2lza29wYXNz # base64 encoded value of 'djangosecretkey'
  DJANGO_DEBUG: dHJ1ZQ==               # base64 encoded value of 'true'
