# celery-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: celery-secret
type: Opaque
data:
  CELERY_BROKER_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzIv # base64 encoded value of 'amqp://guest:guest@rabbitmq:5672/'
