# celery-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: celery-secret
type: Opaque
data:
  CELERY_BROKER_URL: YW1xcDovL3JhYmJpdG1xOjU2NzIv # base64 encoded value of 'amqp://rabbitmq:5672/'
